server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:4406/usthe?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: applesack
  redis:
    port: 7373
