spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql

  # 缓存设置
  redis:
    # 默认服务器索引
    database: 0
    # 默认服务器地址
    host: 127.0.0.1
    # 连接端口
    port: 6379

    jedis:
      pool:
        # 最大连接数
        max-active: 800
        # 最长等待时间
        max-wait: 10000
        # 连接池中最大空闲连接
        max-idle: 20
        # 连接池中最小空闲连接
        min-idle: 2
    timeout: 30000
  cache:
    type: redis

  # banner设置
  banner:
    location: classpath:bootshiro.banner
# mybatis配置
mybatis:
  # 指向实体类包路径
  type-aliases-package: xyz.scootaloo.bootshiro.domian.po
  # mapper xml 文件地址
  mapper-locations: classpath:mapper/*.xml
  # 检查 mybatis 配置是否存在，一般命名为 mybatis-config.xml
  check-config-location: true
  # 执行模式。默认是 SIMPLE
  executor-type: simple

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


########一些应用设置##########

swagger.enable: true
bootshiro.enableEncryptPassword: true