server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://121.5.60.31:4406/usthe?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: applesack
  redis:
    port: 7373
    host: 121.5.60.31
